### ISSUE TITLE
isPaused Flag

### ISSUE THREAD

**Issue by obrunsmann** [amrlabib/react-timer-hook#15]
I suggest an `isPaused` flag like. Currently I need to hold a state besides the timer hook to realize play/pause button.

**Comment by mattgi** [comment]
This feels like something that is really needed? Is there a way currently to determine if a stop watch is running?

`isPaused` or `isRunning` would be very welcomed additions.

**Comment by obrunsmann** [comment]
I added an addtional state hook but this is very dirty and I would appreciate having a flag just out of the timer hook.

**Comment by jordanliu** [comment]
> I added an addtional state hook but this is very dirty and I would appreciate having a flag just out of the timer hook.

isPaused?

**Comment by amrlabib** [comment]
Thank you guys for the issue and sorry for my late response

We have now `isRunning` flag added to both `useTimer` and `useStopwatch` hooks, available from `v2.0.2`
