### ISSUE TITLE
useStopwatch - is skipping 1 minute

### ISSUE THREAD

**Issue by airimia1995** [amrlabib/react-timer-hook#16]

**Comment by technoplato** [comment]
Happening to me too when I try and set the duration on the `useTimer` hook to a multiple of 60 seconds. If I do N minutes - 1 second, I don't see this error.

**Comment by amrlabib** [comment]
Thanks @airimia1995  and @technoplato for the issue and sorry for my late response

Can you please give me more details

1. Simple working example where the issue can be reproduced ? 
2. Which hook is it `useStopwatch` or `useTimer` ?

**Comment by technoplato** [comment]
Seems both. I will provide and example when I get back to my computer.

**Comment by amrlabib** [comment]
Hi @airimia1995 and @technoplato just following up regarding this issue, please let me know if you can give me an example to be able to reproduce the issue and fix it.

Thanks

**Comment by amrlabib** [comment]
I will close this issue until an example is added to be able to reproduce the issue
