### ISSUE TITLE
Widen react-dom peer dependency version requirement

### ISSUE THREAD

**Issue by MasterOdin** [amrlabib/react-timer-hook#39]
Thanks for making this! When installing this module, we get a warning about an unmet peer dependency on react-dom, as it looks like this module is set to require the exact version of `16.8.0`. It seems like this module though works fine with newer versions of `react-dom`, and I wonder if it should be adjusted to be `^16.8.0` like the `react` peer depdendency? For reference, `react-dom 16.8.0` was released in 02/2019, and they are currently up to `16.13.1`.

**Comment by amrlabib** [comment]
Thank you for reporting this, it is fixed now in v2.0.4
