### ISSUE TITLE
Start stopwatch from a given time

### ISSUE THREAD

**Issue by ravindus** [amrlabib/react-timer-hook#42]
I need to start the stopwatch from a given time instead of 0.

example: initial start time is given as 5 minutes, then the stopwatch should start counting up from 5 minutes like` 5:01`, `5:02`, `5:03`

How can I achieve this functionality?

**Comment by amrlabib** [comment]
Thank you for the issue, i updated the library to support `offsetTimestamp` in this [PR](https://github.com/amrlabib/react-timer-hook/pull/43) it is available now in v2.0.7

If you want to start stopwatch with 5 minutes offset you will need to pass the following value in `useStopwatch` settings
```
const offsetTimestamp = new Date(); 
offsetTimestamp.setSeconds(offsetTimestamp.getSeconds() + 300);
```  

You can also check readme file for more details
