### ISSUE TITLE
timer not accurate in mobile

### ISSUE THREAD

**Issue by veeramarni** [amrlabib/react-timer-hook#45]
It seems if I lock my phone and get back to the browser, it slows down and after 5 minutes the timer has just counted 20 seconds. How can the timer can be current after the browser becomes active after it being minimized or phone screen locked?

**Comment by amrlabib** [comment]
Can you please give me more details about this issue it is in `useTimer` right?  is this issue happening only when you use `resume` function ? is it still available in v3.0.0 and above ?

**Comment by veeramarni** [comment]
In my case, I don't want the timer to stop when the browser is not active.  Let say if the browser was not active at the 20th second and I open the browser after 5 minutes, the timer should show the 5 minutes that were passed instead of continuing from the time (from 21 seconds) when the browser was minimized. Is there a way for me to do it?

**Comment by amrlabib** [comment]
Can you please confirm if you are referring to `useStopwatch` or `useTimer` ?

**Comment by veeramarni** [comment]
I'm referring to `useTimer`.

**Comment by amrlabib** [comment]
Then it should work correctly because `useTimer` is working by deciding the current timer state based on expiry timestamp that is passed from settings. this mean that if you take browser to background and then return to foreground it should still show correct time passed.

**Comment by veeramarni** [comment]
@amrlabib I'm using `useStopWatch` and I can reproduce this issue. Can you fix it for `useStopWatch` as well?

**Comment by amrlabib** [comment]
@veeramarni  can you please update the package to the latest version i changed the implementation of `useStopwatch` as well in one of the recent versions so that it will be calculated correctly even if the browser or phone went in background

**Comment by veeramarni** [comment]
I haved checked the demo in my mobile, both useTimer and useStopWatch both get paused in the background whem the browser is not active.

**Comment by veeramarni** [comment]
I guess I found the issue, in iPhone the page gets refreshed automatically when I open it after few hours.
