### ISSUE TITLE
Timer automatically starts

### ISSUE THREAD

**Issue by BronzW** [amrlabib/react-timer-hook#46]
Is there a way to wait for it to start until I call the start() function or does it always automatically start on initialization?

**Comment by amrlabib** [comment]
Yeah right now for `useTimer` it will start automatically on initialization

**Comment by BronzW** [comment]
is there a way to avoid that? just calling pause() won't work because it pauses on every rerender

**Comment by BronzW** [comment]
and why isn't there an autostart property on useTirmer too? useStopwatch has it.

**Comment by rony646** [comment]
@BronzW Did you found a way to solve it? I'm having this problem too

**Comment by BronzW** [comment]
@rony646 I paused it on componentDidMount, not the cleanest thing but works

**Comment by amrlabib** [comment]
I added `autoStart` to `useTimer`, it should be available from v3.0.2 by default the timer will start automatically, so you will need to set the `autoStart` value to `false`
