### ISSUE TITLE
How to stop the timer from outside of the timer component and how to get to the duration when stopped?

### ISSUE THREAD

**Issue by karland** [amrlabib/react-timer-hook#49]
Hi, is there any possibility to stop the timer from outside of the timer component and then to get to the duration when the stop was performed? Thanks a lot.

**Comment by amrlabib** [comment]
Hi, `useTimer` is returning `pause` function , it can be used to pause the timer. regarding duration the timer will always return all time attributes include `seconds`, `minutes`, `hours` and they should reflect the correct values even when the timer is paused.  hope this answers your question

**Comment by DrUlrichAnders** [comment]
Yes it does. Thank you very much.

**Comment by karland** [comment]
Yes, it does. Thank you very much.
