### ISSUE TITLE
useStopwatch not working

### ISSUE THREAD

**Issue by Elir-Mahad** [amrlabib/react-timer-hook#59]
**useStopwatch lags when the counter is runnings**

For testing i followed the below process:
- I started the useStopwatch in my app, and the regular stop watch on my phone, at the same time.
- Then i stopped them at the same time.
- The useStopwatch logged time was 27 minutes. 
- The regular stop watch on my phone's logged time was 1 hour.

I tried this a few more times and the useStopwatch always lagged behind other timers.

**Comment by amrlabib** [comment]
Thank you for flagging this issue, it was mainly related to when browser tab is in background and `setTimeout` and `setInterval` will behave in this state. it is fixed now in v3.0.4
