### ISSUE TITLE
Unnecessary re-rendering

### ISSUE THREAD

**Issue by akpraha** [amrlabib/react-timer-hook#82]
For some inexplicable reason, just using the hook to start a timer causes the component in question to re-render once per second.  If you use the hook in a more complex component, it becomes a huge problem.  At first I thought it might have been because of including the isRunning property from the returned object, but in fact, you don't have to use any of them, and your component will re-render regardless.

The following code snippet exhibits the behavior:

```
let counter = 0;
const HiddenTimer = props => {
    const {
        expiryTimestamp
    } = props;
    console.log("Will expire at " + expiryTimestamp);
    useTimer({expiryTimestamp, onExpire: () => console.log("Timer has expired"), autoStart: true});
    console.log("Timer is being rendered");

    return (
        <div>Counter at {counter++}</div>
    );
};

```
Add it to a simple app and you can observe that it is constantly being needlessly re-rendered.

**Comment by amrlabib** [comment]
Correct me if i am wrong a custom hook is supposed to hold the state of `HiddenTimer` react component right ? an update to the state will cause the re-render so this is expected. For example if you wrap `HiddenTimer` with a parent component example `HiddenTimerParent` and log rendering message inside the parent component we should not see that message every second.

Example:
```
let counter = 0;
const HiddenTimer = props => {
    const {
        expiryTimestamp
    } = props;
    console.log("Will expire at " + expiryTimestamp);
    useTimer({expiryTimestamp, onExpire: () => console.log("Timer has expired"), autoStart: true});
    console.log("Timer is being rendered");

    return (
        <div>Counter at {counter++}</div>
    );
};

const HiddenTimerParent = props => {
  console.log('parent rendering');
  return <HiddenTimer expiryTimestamp={props.expiryTimestamp} />
}
```
In the above code snippet `parent rendering` will not render every second.

`useTimer` is a hook responsible of keeping the state of the react component that is using it.
`HiddenTimer` is the react component using the hook
`HiddenTimerParent` is a parent react component that should not re-render if child component is rendering
