### ISSUE TITLE
TS error Property 'totalSeconds' does not exist on type 'StopwatchResult'

### ISSUE THREAD

**Issue by heorhii-ms** [amrlabib/react-timer-hook#97]

**Comment by kilokeith** [comment]
Added PR to fix this https://github.com/amrlabib/react-timer-hook/pull/98

**Comment by quantotto** [comment]
Hello,
Any chance to merge PR #98 ?
This is a much needed change
Thanks!

**Comment by amrlabib** [comment]
Thank you for flagging and creating the PR. I just merged and published version 3.0.7
